### PR TITLE
Feat/new word definition

### LINKED ISSUE #6: New words: Higher order function
- [ ]  Add definition for new words: higher order function
https://en.wikipedia.org/wiki/Higher-order_function
https://eloquentjavascript.net/05_higher_order.html

### PR DESCRIPTION
**Pull request by Dana94**
Let me know if it needs some edits. 👍 

Closes #6

### CODE REVIEW

**Comment by Cleop** [comment]
nice one @Dana94, thanks for contributing!

@nelsonic - do you have any suggestions for this one or are you happy to merge?

**Review by nelsonic — APPROVED** [review]
@Dana94 this is a good (_succinct_) definition. (thanks!)
@Cleop thanks for reminding about this PR. 
Only thing I would add is an in-line example e.g: https://github.com/dwyl/learn-redux/issues/40#issuecomment-272489779

**Comment by Dana94** [comment]
I can add the example @nelsonic, I'll do this soon.

**Review by iteles — COMMENTED** [review]
Thanks @Dana94 ! This is a very clear and helpful explanation.

@nelsonic Do you think  it might be useful to also add a link to your comment? When learning I've always found that the  kind of 'comparison' you've made where there are side by side definitions of the variations (in this case pure and high order functions) is helpful for charity. However, not sure if you want to be linking to comments in this glossary!

**Comment by iteles** [comment]
@Dana94 Are you up for adding that final reference in so we can merge this in for you? ☺️

**Comment by Dana94** [comment]
Of course @iteles ! To be clear, you are asking to include [dwyl/learn-redux#40 (comment)](https://github.com/dwyl/learn-redux/issues/40#issuecomment-272489779) link somewhere in the definition, correct?

**Comment by iteles** [comment]
That’s exactly it @Dana94, thank you!

**Review by nelsonic — APPROVED** [review]
@Dana94 thanks for adding the definition and link to example. 🎉

**Pull request merged**
